### PR TITLE
Add recently-published papers using FLP data

### PR DESCRIPTION
**Pull request by anseljh**
Also some formatting on previous items

### CODE REVIEW

**Comment by anseljh** [comment]
Closes #42

**Comment by mlissner** [comment]
Is this just the first pass? I feel like there is likely a lot more. What was your method for finding these?

**Comment by anseljh** [comment]
I poked around on SSRN, but that's about it. I agree there are certainly
more.

**Comment by malteos** [comment]
In my recent paper I also used the CL corpus: [Evaluating Document Representations for Content-based Legal Literature Recommendations](https://arxiv.org/abs/2104.13841)

**Comment by mlissner** [comment]
Cool, thanks @malteos. I just added it. It'll show up on our new website once it is ready.

**Pull request merged**
