### PR TITLE
feat(hiring): Take down PM position

### LINKED ISSUE #209: Take down PM position
It should be added to the bottom like the others and the page updated as needed.

### PR DESCRIPTION
**Pull request by elisa-a-v**
Resolves #209 

Added two minor changes not requested in issue:
- Added "Closed" label to closed positions that were missing it.
- Removed a button inviting to apply that was between closed positions (but left the one at the very bottom)

### CODE REVIEW

**Comment by mlissner** [comment]
A few things:

1. Sorry if I was unclear. The closed positions are in order from newest at the top to oldest at the bottom, so this should be at the top of the list, not the bottom.

2. I would have included this in the other PR for this page, so that it didn't create a conflict. I merged the other, but now this one needs some cleanup.

Want to do a little tuning and I'll take another look?

**Comment by mlissner** [comment]
Sorry, the PM position is now closed. Can you tweak accordingly?

**Comment by elisa-a-v** [comment]
> Sorry, the PM position is now closed. Can you tweak accordingly?

I'm not sure what you mean. It's now in the Closed Positions section, wasn't that the issue?

**Comment by mlissner** [comment]
Check the preview: Looks like it's in both: https://deploy-preview-221--freelaw.netlify.app/hiring/

**Comment by elisa-a-v** [comment]
😱 omg how did I miss that, it's fixed now!

**Pull request merged**
