### PR TITLE
feat(donate): Add FAQ page for donations

### PR DESCRIPTION
**Pull request by ERosendo**
This PR adds the FAQ page for donations for free.law

### CODE REVIEW

**Comment by mlissner** [comment]
@jeniferw can you take a look at this and make suggestions and fixes for the new Neon world? We can remove FAQs that aren't needed, and add ones that make sense now. Here's the new page: https://deploy-preview-161--cozy-raindrop-954cef.netlify.app/donate/help/

If you want to do this in a Google doc and have Eduardo do the HTML part of it, that's perfectly OK too. To each their expertise!

**Review by mlissner — CHANGES_REQUESTED** [review]
Once we've got Jenifer's comments merged, the approach looks fine, so please merge once everybody is happy, Eduardo!

**Review by mlissner — APPROVED** [review]

**Comment by mlissner** [comment]
@ERosendo, we got our first round of revisions from Jenifer, here: 

https://docs.google.com/document/d/1tEJKygSBaD96eMDBKbMRnbDS3DXsBm6ISoDUatvtPiE/edit

Can you incorporate these, and then I think I can launch all the donation stuff.

**Comment by ERosendo** [comment]
@mlissner sure!

**Review by mlissner — APPROVED** [review]
I made some tweaks, but it LGTM, thank you. I think we can now deploy/merge all donation-related stuff!

**Comment by mlissner** [comment]
FYI, @jeniferw, this is merged and available at https://free.law/donate/help/. If you want to make changes, please feel free to make a PR if you're up for it, or just make an issue laying things out and we can go from there. Onwards!

**Pull request merged**
