### PR TITLE
Drop flip

### PR DESCRIPTION
**Pull request by flooie**
See Spreadsheet

Updates all logos/svg/pngs/icons
Waiting for approval from Jenifer before I make a full PR (favicon/touch-icons) 

I did the touch/favicons and need to make sure I did it right before turned into a PR

### CODE REVIEW

**Review by mlissner — COMMENTED** [review]
This looks pretty great to me. The one thing I don't understand is the file renames. If you move those files into for-posts, doesn't that break the links to them?

**Comment by flooie** [comment]
@mlissner I updated the PR by removing the for-posts (out of scope) part of the PR.

**Comment by mlissner** [comment]
One last thing, I think: The icon in the footer still shows level scales. Do you have the file to update that?

**Comment by flooie** [comment]
@mlissner - no I do not have a copy of the medium-black flp yet.  The logos is still missing it (I believe)

**Comment by mlissner** [comment]
We've got an open question about whether to drop some smaller images, but I went ahead and merged this since it's a great step forward.

**Pull request merged**
