### PR TITLE
Add Travis CI Support

### PR DESCRIPTION
**Pull request by arichiv**
It works! https://travis-ci.com/arichiv/free.law/builds/85770516?utm_source=github_status&utm_medium=notification

### CODE REVIEW

**Comment by arichiv** [comment]
@mlissner

**Comment by mlissner** [comment]
Hm. Not to be a terrible cynic, but what do we get from this? We publish to AWS typically, so just generating the site...I'm not sure what that accomplishes?

**Comment by arichiv** [comment]
My goal is to automate some test that validates new code actually works. I'm strongly in favor of extending this to fix errors and prevent new ones @mlissner

**Comment by arichiv** [comment]
Ping @mlissner

**Comment by mlissner** [comment]
I'm going to go ahead and merge this one because it seems like a slight improvement, though I'm not sure it makes a huge difference in practice. I'll set this and the other repo up in Travis momentarily, and I think we'll start seeing builds as soon as the next push.

**Pull request merged**
